name: Build and Push Docker image to Docker Hub
'on': push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: 'alekyagandem/workflows:latest'
      - name: SSH to EC2 instance and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.EC2_HOST }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          port: '${{ secrets.EC2_SSH_PORT }}'
          script: |
            docker pull alekyagandem/workflows:latest
      - name: SSH to EC2 instance and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.EC2_HOST }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          port: '${{ secrets.EC2_SSH_PORT }}'
          script: >
            docker stop my-container || true  # Stop the existing container (if
            any)

            docker rm my-container || true    # Remove the existing container
            (if any)

            docker run -d -p 80:80 --name my-container
            alekyagandem/testrepos:latest
